backend/config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  resources :users, only: [:new, :create, :uploadphoto]

  post 'upload' => 'file#post_file'
  get 'requests', to: 'requests#show'
  post 'acceptrequest', to: 'requests#accept'
  root 'sessions#welcome'
  get 'welcome', to: 'sessions#welcome'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'
  post 'sendmessage', to: 'room_messages#new_message'
  post 'change_email', to: 'users#set_email'
  delete 'rooms', to: 'rooms#destroy'
  get 'monitoring_ec2' => 'monitoring#get_ec2_graph'
  get 'monitoring_elb' => 'monitoring#get_elb_graph'
  get 'monitoring_s3' => 'monitoring#get_s3_graph'
end

backend/app/models/room.rb
class Room < ApplicationRecord
    has_many :room_messages, dependent: :destroy,
                         inverse_of: :room
    has_many :request, dependent: :destroy


    def self.cache_key(rooms)
        {
        serializer: 'rooms', 
        start_record: rooms.maximum(:updated_at)
        }
    end

    after_touch :create_json_cache

    private

    def create_json_cache
        CreateRoomsJsonCacheJob.perform_now
    end
end

backend/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :authorized
  # Loads:
  # @rooms = all rooms
  # @room = current room when applicable
  before_action :load_entities
  
  def destroy
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
    @room.destroy
  end

  def index
    @rooms = Room.all
    json = Rails.cache.fetch(Room.cache_key(@rooms)) do 
      @rooms
    end
    render json: json
  end

  def new
    @room = Room.new
  end

  def create
    room_name = params[:name]
    if Room.find_by name: room_name
      return render json: {
        "error": "Another room already has that name"
      }
    else
      params = ActionController::Parameters.new({
        room: {
          name: room_name
        }
      })
      @room = Room.new permitted_parameters
      if @room.save
        render json: @room
      else
        return render json: {
          "error": "error creating room."
        }
      end
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
    room = Room.find_by(id: params[:id])
    if room
      messages = RoomMessage.joins(:room).joins(:user).where(room_id: params[:id]).select('room_messages.*, users.username, users.thumbnail_url')
      # render json: {
      #   "room": room,
      #   "messages": messages
      # }
      json = Rails.cache.fetch('messages') do
        {
          "room": room,
          "messages": messages
        }
      end
    else
      return render json: {
        "error": "room not found"
      }
    end
    render json: json
  end

  def getroommessagespdf
    room = Room.find_by(id: params[:room_id])
    if room
      data = {
        "room": room,
        "messages": room.room_messages.map {
           |msg| {
              "message": msg.message,
              "created_at": msg.created_at,
              "author": msg.user.username
              }
          }
      }
      url_pdf = get_pdf_url(data)
      return render json: {
        "url_pdf": url_pdf
      }
    else
      return render json: {
        "error": "#noroom"
      }
    end
  end

  def get_pdf_url(data)
    form_data = {"data": data}
    form_data = form_data.to_json

    response = HTTParty.post("https://9x3j0lz3cc.execute-api.us-east-1.amazonaws.com/dev/api/htmltopdf", {
      body: form_data,
      headers: {
        'Content-Type' => 'application/json',
        'x-api-key': ENV["AWS_API_HTMLTOPDF_KEY_ID"]
      }
    })
    response_body = JSON.parse(response.body)
    return response_body["url_pdf"]
  end


  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  

  def permitted_parameters
    params.permit(:name)
  end
end

backend/app/helpers/rooms_helper.rb
module RoomsHelper
end

backend/app/views/rooms/index.html.erb
<div class="mb-3">
  <% if @rooms.present? %>
    Select a room or
    <%= link_to new_room_path do %>
      create a room
    <% end %>
  <% else %> 
    <%= link_to new_room_path do %>
      Create a room
    <% end %>
  <% end %>
</div>

<hr/>
<% if @rooms.present? %>
    <table>
      <tr>
        <th>Name</th>
        <th>Created at</th>
      </tr>
        <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %></td>
        <td><%=room.created_at%></td>
      </tr>
          
        <% end %>
    </table>
<% else %>
  <div class="text-muted">
    There are no rooms
  </div>
<% end %>

backend/app/views/rooms/new.html.erb
<h1>Create Room</h1>
  <%= form_for @room do |f|%>
  <%= f.label :name%><br>
  <%= f.text_field :name%><br>
  <%= f.submit %>
<%end%>

backend/app/views/rooms/show.html.erb
<%= link_to 'BACK TO ROOMS LISTS', rooms_path  %>

<h2>
  ROOM NAME: <%= @room.name %>
</h2>
<h3>
  Reload to get new incoming messages!
</h3>
<hr/>

    <div class="chat" style="width:600px; height:300px; overflow: scroll;">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">

            <div class="col">
                <div class="text-right">
                  <small>
                  <%= room_message.user.username %> says at
                    <%= room_message.created_at %>
                  </small>:
                </div>
              <div class="message-content">
                <p class="mb-1">
                  <% if @room[:reversed] %>
                    <%= room_message.message.reverse %>
                  <% else %>
                    <%= room_message.message %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  <%= form_for @room_message do |f|%>
  <%= f.label "New message"%><br>
  <%= f.text_field :message%><br>
  <%= f.hidden_field :room_id %>
  <%= f.submit "Send" %>
<%end%>